server:
  port: 5000
spring:
  application:
    name: vectorx-crowdfunding-project
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  # SpringSession
  session:
    store-type: redis
  # Redis
  redis:
    host: 127.0.0.1
    password: 123456
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
# 自定义 OSS 对象存储服务配置
aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    access-key-id: STS.NTZNCAzYLmkYjomc3Tsa72Nye
    access-key-secret: 8dA4kwJsEwxuEFcGJqTpHsKvnfngaZ7tXzENeXpA2K9A
    security-token: CAIShwJ1q6Ft5B2yfSjIr5fvBfn1l4Zt2qmyaEnchzMBf+4b3YvShzz2IHhMfHNoAu4evvg2nW9R7fcYlr14UZhaSULZa8dx6JsS7w6qf43bq5QUYze9IsT3d1KIAjvXgeXwAYygPv6/F96pb1fb7FwRpZLxaTSlWXG8LJSNkuQJR98LXw6+H1EkbZUsUWkEksIBMmbLPvuAKwPjhnGqbHBloQ1hk2hym8/dq4++kkOO1wKql7ZM/92pcsP6NJBWUc0hA4vv7otfbbHc1SNc0R9O+ZptgbZMkTW95YnFWwMJuEveY7aNq4I2d14jfNQxAalboPbhk/F5vOOWiYn81xFXLfHS1NJH7BhpqxqAAaUwAZWluGmFfvOf8JpnEbF3rVBn3WBBBRY0RZlbvRQ9IZM9ekKcjoT03SCO1m4LBdlSJXaGouu4PlyfAehxBOJOMoF5MFvnjF0LbCc/sU37gPKQRW+WndNp81hovLYZd0DP3LG1PDlA8wi3SBoSGrNhZBohUYQkm6RnG8mb6gXhIAA=
    bucket-name: crowdfunding-vectorx
    bucket-domain: https://crowdfunding-vectorx.oss-cn-shanghai.aliyuncs.com
