server:
  port: 80
spring:
  application:
    name: vectorx-crowdfunding-zuul
  # SpringSession
  session:
    store-type: redis
  # Redis
  redis:
    host: 127.0.0.1
    password: 123456
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
# 网关
zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    crowdfunding-portal:
      service-id: vectorx-crowdfunding-authentication
      path: /**
    crowdfunding-project:
      service-id: vectorx-crowdfunding-project
      path: /project/**
ribbon:
  ConnectTimeout: 10000 # 连接超时时间(ms)
  ReadTimeout: 10000 # 通信超时时间(ms)
