server:
  port: 3000
spring:
  application:
    name: vectorx-crowdfunding-redis
  redis:
    host: 127.0.0.1
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
