server:
  port: 7000
spring:
  application:
    name: vectorx-crowdfunding-pay
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  # SpringSession
  session:
    store-type: redis
  # Redis
  redis:
    host: 127.0.0.1
    password: 123456
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    app-id: 9021000132663643
    merchant-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCNH3i+4g/Q4WstqcFuTOjlMgEUndM7Iqr4bn35wmhAeY5O/0oKdEpf+NoMCit9pxGUNFoEgWKmQvjsbA1Jr6NLCEGznr8YKs9t0IngWblke1QwtYQZUC7LpEDSobvBVq8YZLNo/YsobSfPw/Xdsb5+aTMZy1mXPDXjWWVcmP19kHZf3UOH4rDio8JALk+e0ML7HY84Exwgk8/Yd5KyAjMHgY21gqDghpYjojmEO7pfnfCvdoaE7lJTbAZCDonzGX3yOyCi1XyKMtjj36PJb7iMS8tSW1YCy8J/soPlqKkMD2ZOuhfme/19tOuvXrGw68tsCJ6/pyLTbcpPKp2L3TURAgMBAAECggEAQDrGtfolwKgYI9xTUWRny4kKvNtoPE33CsMfSwGUeWPZxVKj3EY5Y5zbgQdP7AySD6YUImDRCWMJ8HDtS1BJPekwHhRuXQ1/AzgayKWNn5ISK2kyCmNYKQ9FAZji34gYgT2z+mELaQblS8agrJotXVN8Eo1e5VpeHG+flpl7Jh5gAEYajvAr3UHac9hUnOVq8UfdytSPgJp9a6C6WXBELIfWGPTc1CMsiWKRNhGkg+02ME0IJx6eYCZAdi+YHRbWhGUrUlaiH/XWA+l/py5hQFRIP4DIWaja3UQWgSiKMh60JW4dvxnbdm4GEy6sspHWcf3aeyRalyPRZRhM7bu6kQKBgQDTgSZvEM9yTFJw5qSipvt5rd7whwaQ5gJWwJ9mQV6qcJdU6CHQ6XRRa76BCBNrM1sOW+qGeRn0/mL8PKoUmmzK7vnR7tTQN7/TSMan14oa82D/urZw4uqDTeQNF2Ec60CSmVjg/WVhua9WfhTVtvZ+wkx/2sbHz+GdDMyTeqVxvwKBgQCqz9TGnwMV0zRhQ64Py0oc/h+yRV6Sqx6n1SglWXGI9dZ1oOUslE2wKrtKsRHwKvnqEm3jhDxoDcKw/8vOh8AQmnKkbgVfVOMXySw/QrFTuttF6Z2eR8umEFf1Vgd1YPaYoAqSfjAGbVNNS3nal677itXLq1CQ4dlYrdcsT7FtLwKBgQCVSHYJNJNHOGmD+LdBepzK0JcnrBZNVZtXAhRAB2m64UdfDY04uF56TZMj3cBfDNt7MhNBoN5aVuck4+ikLC8XuT8pFuqsoHzLs3VL6E05IolXVsEIwpEF5odNWjAYSk/EaWobO59AL+B7Kvins8EdzSRTpeZiB+9Ve0A14/48XwKBgQCIDRIFQhJLB/booee6XMmjXiYQ8H/rgrDgLT/Uv/FWjblL5+OiJl3au66CR5dqHFECx7sPRPx4RL2WDahf0HCCyQIXRiqxTAO1pl6/5HcpoeOVRAZvU/A5TTtCBkvaimjgGFlTZX8LH3kCT+O24KpXYLX5i3KYc8uSfqSsfq1rsQKBgQCTEA4O16R+athoUiUTQvfzmfY4ShGXmAs4PcgkyWDW4w5ABa76YdZM9gdZ3a7X0M53E8ymZT0ghtB3ipGHTJlPMLLl8N9o8pF+09sjnQol/ywUv92GHnroeIJQhDyQs8tjFFYqIM8dXINA+CCjzOUyZvEYxCPdTisP9c4aQfbhEA==
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp9DhAzI4LGCJuwTQ+9TQn4FOvxUgyeLHheAjejI37DYrfwuEcBND1MlRHTekv0d80FDy962w2nmw4ZhQqCP+it2qSdRt0nszaXYNaZMyx1yDB+ZdQIuPWhwwOkWz6JroGvifZNuMkPbLZmzjd1J9ySd9bAFXmwEw5rinsenC493JXluuEZLCK0ZvdcSBJjfFmJaaZgkQk7+PygTeVbJzcDqfM7NM71t9wg2YOa9vxO8NEqUD5HnM2DSuCd+TRVk1FQ7sQqADY48jskhqrtOUEG7K5KO0nzR7I8Y9HsqstV/HapFcanEqKKJi/wLNb0yzUzsNVBssTBZRxfF6nkeTTQIDAQAB
    notify_url: http://jvidwm.natappfree.cc/pay/notify
    return_url: http://localhost/pay/return
    sign_type: RSA2
    charset: utf-8
    gateway-url:  https://openapi-sandbox.dl.alipaydev.com/gateway.do
