server:
  port: 7000
spring:
  application:
    name: vectorx-consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
feign:
  hystrix:
    enabled: true  #降级
